name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: ap
      run: sudo apt update && sudo apt install ninja-build liblua5.1-0-dev liblua5.2-dev liblua5.3-dev libluajit-5.1-dev libncursesw5-dev zlib1g-dev libsdl2-dev libsdl2-ttf-dev imagemagick libwxgtk3.0-gtk3-dev
    - name: make
      run: |
        ./configure dev
        make

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: brew
      run: brew install pkg-config ninja SDL2_ttf SDL2 imagemagick wxwidgets
    - name: make
      run: |
        ./configure
        make

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install >-
          make
          mingw-w64-cross-gcc
          mingw-w64-i686-SDL
          mingw-w64-i686-SDL2_ttf
          mingw-w64-i686-brotli
          mingw-w64-i686-imagemagick
          mingw-w64-i686-nsis
          mingw-w64-i686-pkg-config
          mingw-w64-i686-wxWidgets
          mingw-w64-i686-zlib
          ninja
          vim
          zip
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: build
      run: |
        PATH=/mingw32/bin:/opt/bin:$PATH ./configure
        PATH=/mingw32/bin:/opt/bin:$PATH make
    - name: zip
      run: |
        zip -9 wordgrinder-windows.zip bin/WordGrinder-*-setup.exe
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}.${{ github.sha }}
        path: wordgrinder-windows.zip

