name: Autorelease

on:
  push:
    branches:
      - "master"

jobs:
  dev-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MINGW32
        install: >-
          make
          mingw-w64-i686-binutils
          mingw-w64-i686-fmt
          mingw-w64-i686-gcc
          mingw-w64-i686-glfw
          mingw-w64-i686-imagemagick
          mingw-w64-i686-nsis
          mingw-w64-i686-pkg-config
          mingw-w64-i686-zlib
          mingw-w64-i686-cmark
          ninja
          python3
          tar
          vim
          zip
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: build
      run: |
        PATH=/mingw32/bin:/opt/bin:$PATH MAGICK_TIME_LIMIT=100 make all debian-distr
    - name: tag
      uses: EndBug/latest-tag@latest
      with:
        tag-name: dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: delete-old-assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: dev
        assets: | 
          bin/wordgrinder-*.tar.xz
          bin/WordGrinder-*-setup.exe
        fail-if-no-assets: false
    - name: date
      run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        name: Development build ${{ env.RELEASE_DATE }}
        files: |
          bin/wordgrinder-*.tar.xz
          bin/WordGrinder-*-setup.exe
        tag_name: dev
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
